version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: movies
      MYSQL_USER: tony
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - ~/dbs/mysql:/var/lib/mysql
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge
